/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f8fafb',
        'surface-dim': '#d8dadb',
        'surface-bright': '#f8fafb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f5',
        'surface-container': '#eceeef',
        'surface-container-high': '#e6e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#3f484b',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#eff1f2',
        outline: '#6f797c',
        'outline-variant': '#bec8cb',
        'surface-tint': '#086878',
        primary: '#006474',
        'on-primary': '#ffffff',
        'primary-container': '#2d7d8e',
        'on-primary-container': '#f3fcff',
        'inverse-primary': '#87d2e4',
        secondary: '#436182',
        'on-secondary': '#ffffff',
        'secondary-container': '#b9d7fd',
        'on-secondary-container': '#405e7e',
        tertiary: '#7e5200',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#9f6800',
        'on-tertiary-container': '#fffaf8',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#a9edff',
        'primary-fixed-dim': '#87d2e4',
        'on-primary-fixed': '#001f26',
        'on-primary-fixed-variant': '#004e5b',
        'secondary-fixed': '#d1e4ff',
        'secondary-fixed-dim': '#abc9ef',
        'on-secondary-fixed': '#001d35',
        'on-secondary-fixed-variant': '#2a4968',
        'tertiary-fixed': '#ffddb4',
        'tertiary-fixed-dim': '#ffb955',
        'on-tertiary-fixed': '#291800',
        'on-tertiary-fixed-variant': '#633f00',
        background: '#f8fafb',
        'on-background': '#191c1d',
        'surface-variant': '#e1e3e4'
      },
      fontFamily: {
        sans: ['"Open Sans"', 'sans-serif']
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px'
      },
      spacing: {
        'unit': '8px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
        'container-max': '800px',
        'sidebar-width': '260px',
        'sidebar-collapsed': '72px'
      }
    },
  },
  plugins: [],
}
